Repository gbif/hp-beaty-biodiversity-museum, pull requests merged in 2024-02, with the labels that each got.

#94 issue-93
  pages/home.md
Labels: organization, user-interface

#97 Issue 96
  _data/datasets.yml
  _includes/js/config.js
  pages/home.md
Labels: enhancement, organization, user-interface

#99 Add or language below search
  _sass/_home.scss
  pages/home.md
Labels: user-interface

#100 Add some space to the paragraph under Collections on homepage
  _sass/_main.scss
Labels: user-interface
